Use the official discourse metrics exporter
canonical/discourse-k8s-operator pull request #99
Opened 2023-09-01 20:29 UTC by nrobinaubertin

![image](https://github.com/canonical/discourse-k8s-operator/assets/5983763/6a1cd93e-f5c7-4350-b98a-b9a80f57c3f2)

The [previous used exporter](https://github.com/discourse/prometheus_exporter) didn't give us the default metrics we would want and forces us to create custom collectors.  
I replaced it with the official exporter plugin that gives us a lot of metrics out of the box.

This is meant to be a small incremental update. We could add more extensive tests in a subsequent PR (like adding some form of grafana dashboard linting).

2023-09-04 03:14 UTC, weiiwang01 approved these changes

2023-09-04 05:28 UTC, jdkandersson requested changes
Please ensure that ISD062 is being followed in these PRs

2023-09-04 06:57 UTC, merkata approved these changes
This looks very good! Please add a label to the PR and for now you could copy a check list of items like [here](https://github.com/canonical/synapse-operator/pull/30). We can add a template later, I'm hoping via terraform. though that's a different discussion.

2023-09-04 15:35 UTC, arturo-seijas approved these changes
LGTM

2023-09-04 20:19 UTC, amandahla approved these changes
LGTM

2023-09-05 01:14 UTC, yanksyoon approved these changes
LGTM!

2023-09-05 03:37 UTC, jdkandersson commented
> Please ensure that ISD062 is being followed in these PRs

There seems to be a lot of unchecked items, could an explanation for those please provided?

2023-09-05 06:44 UTC, merkata commented
> This looks very good! Please add a label to the PR and for now you could copy a check list of items like [here](https://github.com/canonical/synapse-operator/pull/30). We can add a template later, I'm hoping via terraform. though that's a different discussion.

@nrobinaubertin Please note that if a checkbox is not applicable, you should check it and not leave it empty. Leaving it empty leaves the impression it is not done yet, marking it signals it is either done or not applicable for this PR. Thanks!

2023-09-05 10:47 UTC, nrobinaubertin commented
> > This looks very good! Please add a label to the PR and for now you could copy a check list of items like [here](https://github.com/canonical/synapse-operator/pull/30). We can add a template later, I'm hoping via terraform. though that's a different discussion.
> 
> @nrobinaubertin Please note that if a checkbox is not applicable, you should check it and not leave it empty. Leaving it empty leaves the impression it is not done yet, marking it signals it is either done or not applicable for this PR. Thanks!

I thought that they stood for the repo. I've checked all the boxes then since they're not really applicable for this PR then.

2023-09-07 01:04 UTC, jdkandersson approved these changes

2023-09-07 02:45 UTC, merged